"""Configuration constants for the ElektroScan detector."""

from __future__ import annotations

import os

import cv2
import numpy as np


def _safe_cpu_count() -> int:
    """Return a sane positive CPU count fallback."""

    return max(1, int(os.cpu_count() or 1))


def _default_detector_workers() -> int:
    """Use available logical cores while keeping OpenCV internal threading low."""

    return _safe_cpu_count()


def _env_int(name: str, default: int, *, minimum: int = 1) -> int:
    """Read an integer env var safely."""

    raw = os.getenv(name)
    if raw is None or raw == "":
        return max(minimum, default)
    try:
        return max(minimum, int(raw))
    except ValueError:
        return max(minimum, default)


DETECTOR_SCAN_MAX_WORKERS = _env_int(
    "ELEKTROSCAN_DETECTOR_SCAN_WORKERS",
    _default_detector_workers(),
)
DETECTOR_POSTPROCESS_MAX_WORKERS = _env_int(
    "ELEKTROSCAN_DETECTOR_POSTPROCESS_WORKERS",
    _default_detector_workers(),
)
OPENCV_NUM_THREADS = _env_int("ELEKTROSCAN_OPENCV_THREADS", 1)

try:
    cv2.setNumThreads(OPENCV_NUM_THREADS)
except Exception:
    pass


HSV_LOWER = np.array([0, 30, 50])
HSV_UPPER = np.array([180, 255, 255])

DILATE_KERNEL = np.ones((3, 3), np.uint8)

ROTATIONS = [
    (0, None),
    (90, cv2.ROTATE_90_CLOCKWISE),
    (180, cv2.ROTATE_180),
    (270, cv2.ROTATE_90_COUNTERCLOCKWISE),
]
SCALES = [0.90, 1.00, 1.10]

THRESHOLD_PRECISE = 0.55
THRESHOLD_DILATED = 0.45
TEXT_CONTENT_THRESHOLD = 0.58

MAX_PEAKS_PER_VARIANT = 1500
MAX_TEXT_CONTENT_PEAKS_PER_VARIANT = 500
MIN_TEMPLATE_PIXELS = 20

MIN_COVERAGE_RATIO = 0.24
MIN_PURITY_RATIO = 0.08
MIN_CONTEXT_PURITY = 0.72
MIN_VERIFICATION_SCORE = 0.40
MAX_CENTROID_OFFSET_RATIO = 0.18
LOW_MATCH_STRICT_THRESHOLD = 0.58
CONTEXT_MARGIN_RATIO = 0.40

LOCAL_MAX_KERNEL_RATIO = 0.25

ROI_COMPONENT_DILATE_PIXELS = 9
ROI_MIN_COMPONENT_PIXELS = 6
ROI_MAX_COMPONENTS = 1200
ROI_MERGE_GAP_PIXELS = 4
ROI_PADDING_RATIO = 1.15
ROI_FULL_SCAN_AREA_RATIO = 0.70

PRECISE_KEYWORDS = ["gniazdo", "wypust"]
MIRRORED_VARIANT_PREFIXES = {"06", "07", "09", "10", "11", "12"}

COLOR_HUE_TOLERANCE = 18
COLOR_SAT_TOLERANCE = 80
COLOR_VAL_TOLERANCE = 80
COLOR_HUE_REJECTION_THRESHOLD = 36
SOCKET_07_EXTRA_MIN_COVERAGE = 0.30
SOCKET_07_PROMOTION_SEARCH_RADIUS = 4
SOCKET_PROMOTED_MAX_VERIFICATION_DROP = 0.05
SOCKET_07_STRONG_EXTRA_COVERAGE = 0.60
SOCKET_07_STRONG_MIN_COVERAGE = 0.80
SOCKET_07_STRONG_MIN_CONTEXT_PURITY = 0.25
SOCKET_07_STRONG_MAX_VERIFICATION_DROP = 0.16
SWITCH_10_EXTRA_MIN_COVERAGE = 0.18
SWITCH_12_EXTRA_MIN_COVERAGE = 0.18
SWITCH_PROMOTION_SEARCH_RADIUS = 8
SWITCH_FAMILY_MIN_CHILD_COVERAGE = 0.62
SWITCH_FAMILY_MIN_CROP_PURITY = 0.90
SWITCH_PROMOTED_MIN_PURITY = 0.58
SWITCH_PROMOTED_MIN_CONTEXT_PURITY = 0.22
SWITCH_PROMOTED_MIN_VERIFICATION = 0.62
SWITCH_10_PROMOTED_MAX_VERIFICATION_DROP = 0.06
SWITCH_12_PROMOTED_MAX_VERIFICATION_DROP = 0.18
SWITCH_PARENT_FALLBACK_SEARCH_RADIUS = 18
PROMOTED_PARENT_MIN_VERIFICATION = 0.68
PROMOTED_PARENT_OVERRIDE_MARGIN = 0.16
PROMOTED_PARENT_MIN_AREA_RATIO = 1.10
NOISY_PARTIAL_CONTEXT_THRESHOLD = 0.36
NOISY_PARTIAL_COVERAGE_THRESHOLD = 0.67
NOISY_PARTIAL_PURITY_THRESHOLD = 0.88

LABEL_TEMPLATE_MIN_ASPECT_RATIO = 1.25
LABEL_TEMPLATE_MIN_WIDTH = 40
LABEL_TEMPLATE_MAX_AREA = 5000
LABEL_LINE_MIN_RATIO = 0.18
LABEL_CONTENT_MIN_PIXELS = 18
LABEL_CONTENT_MIN_RATIO = 0.06
LABEL_CONTENT_MAX_RATIO = 0.72
LABEL_CONTENT_MIN_SCORE = 0.60
LABEL_FULL_WIDTH_CONTENT_MIN_SCORE = 0.50
LABEL_CONTENT_SCORE_WEIGHT = 0.55
LABEL_CONTENT_SCAN_MIN_PIXELS = 180
TEXT_LABEL_FULLER_AREA_RATIO = 1.12
TEXT_LABEL_FULLER_MAX_CONTENT_DROP = 0.08
TEXT_LABEL_FULLER_MAX_VERIFICATION_DROP = 0.08

PREFILTER_NMS_MIN_CANDIDATES = 250
PREFILTER_NMS_IOU_THRESHOLD = 0.85
RAW_PREFILTER_MIN_CANDIDATES = 1200
RAW_PREFILTER_IOU_THRESHOLD = 0.98
RAW_PREFILTER_IOM_THRESHOLD = 0.995
RAW_PREFILTER_CENTER_DISTANCE_RATIO = 0.04

CLUSTER_IOU_THRESHOLD = 0.30
CLUSTER_IOM_THRESHOLD = 0.72
CLUSTER_CENTER_DISTANCE_RATIO = 0.28
CROSS_COLOR_CLUSTER_IOU_THRESHOLD = 0.55
CROSS_COLOR_CLUSTER_IOM_THRESHOLD = 0.88
CROSS_COLOR_CENTER_DISTANCE_RATIO = 0.16

DEBUG_CANDIDATES_LIMIT = 64
DEBUG_ACCEPTED_UNCERTAIN_CANDIDATES_LIMIT = 32
DEBUG_CONFLICT_CANDIDATES_LIMIT = 6
DEBUG_UNEXPLAINED_CANDIDATES_LIMIT = 18
DEBUG_UNEXPLAINED_PER_UNCERTAIN_BOX = 3
DEBUG_REJECTED_CANDIDATES_LIMIT = 24
DEBUG_REJECTED_MIN_MATCH = 0.56
DEBUG_ACCEPTED_UNCERTAIN_MAX_SCORE = 0.66
DEBUG_ACCEPTED_UNCERTAIN_MAX_CONTEXT_PURITY = 0.42
DEBUG_ACCEPTED_UNCERTAIN_NEARBY_PX = 72
DEBUG_NEAR_UNCERTAIN_COMPONENT_PX = 90
DEBUG_CONFLICT_MIN_IOM = 0.45
DEBUG_CONFLICT_MAX_SCORE_DROP = 0.04
DEBUG_UNEXPLAINED_MIN_AREA = 45
DEBUG_UNEXPLAINED_MAX_AREA = 12000

DEFAULT_PDF_DPI = 300
PDF_TEXT_MIN_TOKEN_LENGTH = 2
PDF_TEXT_MAX_TOKEN_LENGTH = 6
LEGEND_KEYWORD = "LEGENDA"
LEGEND_WIDTH_PT = 300
LEGEND_HEIGHT_PT = 550
