"""Configuration constants for the ElektroScan detector."""

from __future__ import annotations

import os

import cv2
import numpy as np


def _safe_cpu_count() -> int:
    """Return a sane positive CPU count fallback."""

    return max(1, int(os.cpu_count() or 1))


def _default_opencv_threads() -> int:
    """Keep OpenCV single-threaded while Python spreads variant scan tasks."""

    return 1


def _default_detector_workers() -> int:
    """Use available logical cores with single-threaded OpenCV calls."""

    return _safe_cpu_count()


def _env_int(name: str, default: int, *, minimum: int = 1) -> int:
    """Read an integer env var safely."""

    raw = os.getenv(name)
    if raw is None or raw == "":
        return max(minimum, default)
    try:
        return max(minimum, int(raw))
    except ValueError:
        return max(minimum, default)


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or raw == "":
        return default
    try:
        return float(raw)
    except ValueError:
        return default


DETECTOR_SCAN_MAX_WORKERS = _env_int(
    "ELEKTROSCAN_DETECTOR_SCAN_WORKERS",
    _default_detector_workers(),
)
GRAY_SCAN_MAX_WORKERS = _env_int(
    "ELEKTROSCAN_GRAY_SCAN_WORKERS",
    min(_safe_cpu_count(), 12),
)
DETECTOR_POSTPROCESS_MAX_WORKERS = _env_int(
    "ELEKTROSCAN_DETECTOR_POSTPROCESS_WORKERS",
    _default_detector_workers(),
)
OPENCV_NUM_THREADS = _env_int("ELEKTROSCAN_OPENCV_THREADS", _default_opencv_threads())

try:
    cv2.setNumThreads(OPENCV_NUM_THREADS)
except Exception:
    pass


HSV_LOWER = np.array([0, 30, 50])
HSV_UPPER = np.array([180, 255, 255])

DILATE_KERNEL = np.ones((3, 3), np.uint8)

ROTATIONS = [
    (0, None),
    (90, cv2.ROTATE_90_CLOCKWISE),
    (180, cv2.ROTATE_180),
    (270, cv2.ROTATE_90_COUNTERCLOCKWISE),
]
GRAY_DIAGONAL_ROTATIONS = [
    15,
    45,
    75,
    105,
    135,
    165,
    195,
    225,
    255,
    285,
    315,
    345,
]
GRAY_DIAGONAL_ROTATION_MIN_SCALE = _env_float(
    "ELEKTROSCAN_GRAY_DIAGONAL_ROTATION_MIN_SCALE", 0.8
)
GRAY_DIAGONAL_ROTATION_MIN_ASPECT = _env_float(
    "ELEKTROSCAN_GRAY_DIAGONAL_ROTATION_MIN_ASPECT", 2.0
)
GRAY_DIAGONAL_ROTATION_MAX_TEMPLATE_PIXELS = _env_int(
    "ELEKTROSCAN_GRAY_DIAGONAL_ROTATION_MAX_TEMPLATE_PIXELS", 1200
)
SCALES = [0.90, 1.00, 1.10]
# Diagnostic wider scales used only when detector_profile == "gray".
# Symbols on gray plans are often rendered much smaller than the legend templates.
# This range intentionally extends down to 0.5 so we can see at which scale
# raw_peaks first appear; once that is known, set a tighter GRAY_SCALES.
GRAY_SCALES = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2]

THRESHOLD_PRECISE = 0.55
THRESHOLD_DILATED = 0.45
TEXT_CONTENT_THRESHOLD = 0.58

MAX_PEAKS_PER_VARIANT = 1500
MAX_TEXT_CONTENT_PEAKS_PER_VARIANT = 500
GRAY_SEARCH_MAX_ROIS = _env_int("ELEKTROSCAN_GRAY_SEARCH_MAX_ROIS", 360)
GRAY_SEARCH_TILE_SIZE = _env_int("ELEKTROSCAN_GRAY_SEARCH_TILE_SIZE", 512)
GRAY_SEARCH_TILE_PADDING = _env_int("ELEKTROSCAN_GRAY_SEARCH_TILE_PADDING", 24)
GRAY_SEARCH_TILE_MIN_FOREGROUND = _env_int("ELEKTROSCAN_GRAY_SEARCH_TILE_MIN_FOREGROUND", 12)
GRAY_SEARCH_MAX_TILE_ROIS = _env_int("ELEKTROSCAN_GRAY_SEARCH_MAX_TILE_ROIS", 60)
GRAY_SEARCH_COMPONENT_PADDING_RATIO = _env_float(
    "ELEKTROSCAN_GRAY_SEARCH_COMPONENT_PADDING_RATIO", 0.85
)
GRAY_SEARCH_COMPONENT_DILATE_ITERATIONS = _env_int(
    "ELEKTROSCAN_GRAY_SEARCH_COMPONENT_DILATE_ITERATIONS", 2, minimum=0
)
GRAY_SEARCH_ROI_CONTAINMENT_THRESHOLD = _env_float(
    "ELEKTROSCAN_GRAY_SEARCH_ROI_CONTAINMENT_THRESHOLD", 0.92
)
GRAY_SEARCH_ROI_OVERLAP_THRESHOLD = _env_float(
    "ELEKTROSCAN_GRAY_SEARCH_ROI_OVERLAP_THRESHOLD", 0.82
)
GRAY_SPATIAL_FAIR_PEAKS_PER_ROI = _env_int("ELEKTROSCAN_GRAY_SPATIAL_FAIR_PEAKS_PER_ROI", 6)
GRAY_SCAN_MIN_ROI_FOREGROUND_RATIO = _env_float(
    "ELEKTROSCAN_GRAY_SCAN_MIN_ROI_FOREGROUND_RATIO", 0.50
)
GRAY_RAW_MAX_HITS_PER_VARIANT = _env_int("ELEKTROSCAN_GRAY_RAW_MAX_HITS_PER_VARIANT", 180)
GRAY_RAW_MAX_HITS_PER_TEMPLATE = _env_int("ELEKTROSCAN_GRAY_RAW_MAX_HITS_PER_TEMPLATE", 1200)
GRAY_RAW_MAX_TOTAL_HITS = _env_int("ELEKTROSCAN_GRAY_RAW_MAX_TOTAL_HITS", 9000)
GRAY_RAW_MIN_HITS_PER_TEMPLATE = _env_int("ELEKTROSCAN_GRAY_RAW_MIN_HITS_PER_TEMPLATE", 80)

# Large/complex gray templates (for example framed labels) lose too much signal
# when long-stroke suppression removes their frame. Use raw ink for scanning
# those shapes while keeping suppression for small sparse stroke templates.
GRAY_RAW_SCAN_MIN_TEMPLATE_AREA = _env_int("ELEKTROSCAN_GRAY_RAW_SCAN_MIN_TEMPLATE_AREA", 6000)
GRAY_RAW_SCAN_MIN_TEMPLATE_PIXELS = _env_int("ELEKTROSCAN_GRAY_RAW_SCAN_MIN_TEMPLATE_PIXELS", 1000)
GRAY_RAW_SCAN_THRESHOLD = _env_float("ELEKTROSCAN_GRAY_RAW_SCAN_THRESHOLD", 0.52)
GRAY_STRICT_SCAN_THRESHOLD = _env_float("ELEKTROSCAN_GRAY_STRICT_SCAN_THRESHOLD", 0.57)
GRAY_RECT_FRAME_MIN_ASPECT = _env_float("ELEKTROSCAN_GRAY_RECT_FRAME_MIN_ASPECT", 2.0)
GRAY_RECT_FRAME_MIN_DENSITY = _env_float("ELEKTROSCAN_GRAY_RECT_FRAME_MIN_DENSITY", 0.48)
GRAY_RECT_FRAME_MAX_DENSITY = _env_float("ELEKTROSCAN_GRAY_RECT_FRAME_MAX_DENSITY", 0.70)
GRAY_RECT_FRAME_MIN_RAW_SCAN_SCALE = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_MIN_RAW_SCAN_SCALE", 1.0
)
GRAY_RECT_FRAME_MAX_RAW_SCAN_SCALE = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_MAX_RAW_SCAN_SCALE", 1.1
)
GRAY_RECT_FRAME_STRONG_EDGE_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_STRONG_EDGE_COVERAGE", 0.60
)
GRAY_RECT_FRAME_WEAK_EDGE_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_WEAK_EDGE_COVERAGE", 0.25
)
GRAY_RECT_FRAME_MAX_CENTER_DENSITY = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_MAX_CENTER_DENSITY", 0.28
)
GRAY_RECT_FRAME_LONG_EDGE_MIN_RUN = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_LONG_EDGE_MIN_RUN", 0.65
)
GRAY_RECT_FRAME_SHORT_EDGE_STRONG_RUN = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_SHORT_EDGE_STRONG_RUN", 0.55
)
GRAY_RECT_FRAME_SHORT_EDGE_WEAK_RUN = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_SHORT_EDGE_WEAK_RUN", 0.14
)
GRAY_RECT_FRAME_MERGE_IOM = _env_float("ELEKTROSCAN_GRAY_RECT_FRAME_MERGE_IOM", 0.55)
GRAY_RECT_FRAME_MERGE_CENTER_DISTANCE = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_MERGE_CENTER_DISTANCE", 0.50
)
GRAY_RECT_FRAME_MERGE_MAX_SCALE_DELTA = _env_float(
    "ELEKTROSCAN_GRAY_RECT_FRAME_MERGE_MAX_SCALE_DELTA", 0.20
)
GRAY_ELONGATED_SCAN_THRESHOLD = _env_float("ELEKTROSCAN_GRAY_ELONGATED_SCAN_THRESHOLD", 0.30)
GRAY_ELONGATED_SCAN_MAX_TEMPLATE_PIXELS = _env_int(
    "ELEKTROSCAN_GRAY_ELONGATED_SCAN_MAX_TEMPLATE_PIXELS", 800
)
GRAY_DARK_INK_THRESHOLD = _env_int("ELEKTROSCAN_GRAY_DARK_INK_THRESHOLD", 170)
GRAY_DARK_ZONE_THRESHOLD = _env_int("ELEKTROSCAN_GRAY_DARK_ZONE_THRESHOLD", 130)
GRAY_DARK_EVIDENCE_THRESHOLD = _env_int("ELEKTROSCAN_GRAY_DARK_EVIDENCE_THRESHOLD", 105)
GRAY_LEGEND_INK_PERCENTILE = _env_float("ELEKTROSCAN_GRAY_LEGEND_INK_PERCENTILE", 75.0)
GRAY_LEGEND_ZONE_MARGIN = _env_int("ELEKTROSCAN_GRAY_LEGEND_ZONE_MARGIN", 10)
GRAY_LEGEND_EVIDENCE_MARGIN = _env_int("ELEKTROSCAN_GRAY_LEGEND_EVIDENCE_MARGIN", 0)
GRAY_LEGEND_DARK_MARGIN = _env_int("ELEKTROSCAN_GRAY_LEGEND_DARK_MARGIN", 30)
GRAY_LEGEND_MIN_ZONE_THRESHOLD = _env_int("ELEKTROSCAN_GRAY_LEGEND_MIN_ZONE_THRESHOLD", 105)
GRAY_LEGEND_MIN_EVIDENCE_THRESHOLD = _env_int(
    "ELEKTROSCAN_GRAY_LEGEND_MIN_EVIDENCE_THRESHOLD", 80
)
GRAY_DARK_EVIDENCE_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_DARK_EVIDENCE_MIN_COVERAGE", 0.62
)
GRAY_DARK_EVIDENCE_MIN_PIXELS = _env_int("ELEKTROSCAN_GRAY_DARK_EVIDENCE_MIN_PIXELS", 10)
GRAY_COHERENT_INK_MIN_MATCH = _env_float("ELEKTROSCAN_GRAY_COHERENT_INK_MIN_MATCH", 0.55)
GRAY_COHERENT_INK_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_COHERENT_INK_MIN_COVERAGE", 0.67
)
GRAY_COHERENT_INK_MIN_PURITY = _env_float("ELEKTROSCAN_GRAY_COHERENT_INK_MIN_PURITY", 0.70)
GRAY_COHERENT_INK_MIN_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_COHERENT_INK_MIN_CONTEXT", 0.35
)
GRAY_COHERENT_INK_MIN_SCALE = _env_float("ELEKTROSCAN_GRAY_COHERENT_INK_MIN_SCALE", 0.75)
GRAY_COHERENT_INK_ELONGATED_ASPECT = _env_float(
    "ELEKTROSCAN_GRAY_COHERENT_INK_ELONGATED_ASPECT", 2.0
)
GRAY_COHERENT_INK_ELONGATED_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_COHERENT_INK_ELONGATED_MIN_COVERAGE", 0.82
)
GRAY_ANGLED_INK_MIN_MATCH = _env_float("ELEKTROSCAN_GRAY_ANGLED_INK_MIN_MATCH", 0.65)
GRAY_ANGLED_INK_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_ANGLED_INK_MIN_COVERAGE", 0.88
)
GRAY_ANGLED_INK_MIN_PURITY = _env_float("ELEKTROSCAN_GRAY_ANGLED_INK_MIN_PURITY", 0.30)
GRAY_ANGLED_INK_MIN_CONTEXT = _env_float("ELEKTROSCAN_GRAY_ANGLED_INK_MIN_CONTEXT", 0.13)
GRAY_ANGLED_INK_MIN_SCALE = _env_float("ELEKTROSCAN_GRAY_ANGLED_INK_MIN_SCALE", 0.80)
GRAY_ANGLED_INK_STRONG_MIN_MATCH = _env_float(
    "ELEKTROSCAN_GRAY_ANGLED_INK_STRONG_MIN_MATCH", 0.74
)
GRAY_ANGLED_INK_STRONG_MIN_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_ANGLED_INK_STRONG_MIN_CONTEXT", 0.10
)


# Gray small-scale anomaly filter: rejects only the conjunction of
# (low coverage AND anomalously high purity), the signature of a sparse
# template that latched onto an isolated stroke fragment.  Set
# ELEKTROSCAN_GRAY_SMALL_SCALE_SUSPICIOUS_PURITY=1.01 to disable.
GRAY_SMALL_SCALE_THRESHOLD = _env_float("ELEKTROSCAN_GRAY_SMALL_SCALE_THRESHOLD", 0.7)
GRAY_SMALL_SCALE_MIN_COVERAGE = _env_float("ELEKTROSCAN_GRAY_SMALL_SCALE_MIN_COVERAGE", 0.80)
GRAY_SMALL_SCALE_SUSPICIOUS_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_SUSPICIOUS_PURITY", 0.85
)
GRAY_SMALL_SCALE_ELONGATED_ASPECT = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_ELONGATED_ASPECT", 2.0
)
GRAY_SMALL_SCALE_ELONGATED_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_ELONGATED_MIN_COVERAGE", 0.80
)
GRAY_SMALL_SCALE_ELONGATED_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_ELONGATED_MIN_PURITY", 0.40
)
GRAY_SMALL_SCALE_ELONGATED_MIN_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_ELONGATED_MIN_CONTEXT", 0.12
)
GRAY_SMALL_SCALE_ELONGATED_MAX_DENSITY = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_ELONGATED_MAX_DENSITY", 0.35
)
GRAY_SMALL_SCALE_COMPACT_MAX_ASPECT = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_COMPACT_MAX_ASPECT", 1.35
)
GRAY_SMALL_SCALE_COMPACT_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_COMPACT_MIN_COVERAGE", 0.82
)
GRAY_STRONG_GEOMETRY_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_STRONG_GEOMETRY_MIN_COVERAGE", 0.94
)
GRAY_STRONG_GEOMETRY_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_STRONG_GEOMETRY_MIN_PURITY", 0.50
)
GRAY_STRONG_GEOMETRY_MIN_MATCH = _env_float(
    "ELEKTROSCAN_GRAY_STRONG_GEOMETRY_MIN_MATCH", 0.54
)
GRAY_STRONG_RESCUE_MIN_VERIFICATION = _env_float(
    "ELEKTROSCAN_GRAY_STRONG_RESCUE_MIN_VERIFICATION", 0.60
)
GRAY_STRONG_RESCUE_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_STRONG_RESCUE_MIN_PURITY", 0.40
)
GRAY_COMPLEX_GEOMETRY_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_COMPLEX_GEOMETRY_MIN_COVERAGE", 0.86
)
GRAY_COMPLEX_GEOMETRY_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_COMPLEX_GEOMETRY_MIN_PURITY", 0.55
)
GRAY_COMPLEX_GEOMETRY_MIN_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_COMPLEX_GEOMETRY_MIN_CONTEXT", 0.30
)
GRAY_MID_GEOMETRY_MIN_TEMPLATE_PIXELS = _env_int(
    "ELEKTROSCAN_GRAY_MID_GEOMETRY_MIN_TEMPLATE_PIXELS", 700
)
GRAY_MID_GEOMETRY_MIN_MATCH = _env_float("ELEKTROSCAN_GRAY_MID_GEOMETRY_MIN_MATCH", 0.64)
GRAY_MID_GEOMETRY_MIN_VERIFICATION = _env_float(
    "ELEKTROSCAN_GRAY_MID_GEOMETRY_MIN_VERIFICATION", 0.64
)
GRAY_MID_GEOMETRY_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_MID_GEOMETRY_MIN_COVERAGE", 0.96
)
GRAY_MID_GEOMETRY_MIN_PURITY = _env_float("ELEKTROSCAN_GRAY_MID_GEOMETRY_MIN_PURITY", 0.60)
GRAY_MID_GEOMETRY_MIN_CONTEXT = _env_float("ELEKTROSCAN_GRAY_MID_GEOMETRY_MIN_CONTEXT", 0.28)
GRAY_LABEL_GEOMETRY_MIN_MATCH = _env_float(
    "ELEKTROSCAN_GRAY_LABEL_GEOMETRY_MIN_MATCH", 0.74
)
GRAY_LABEL_GEOMETRY_MIN_VERIFICATION = _env_float(
    "ELEKTROSCAN_GRAY_LABEL_GEOMETRY_MIN_VERIFICATION", 0.68
)
GRAY_LABEL_GEOMETRY_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_LABEL_GEOMETRY_MIN_COVERAGE", 0.88
)
GRAY_LABEL_GEOMETRY_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_LABEL_GEOMETRY_MIN_PURITY", 0.70
)
GRAY_LABEL_GEOMETRY_MIN_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_LABEL_GEOMETRY_MIN_CONTEXT", 0.44
)
GRAY_WEAK_LABEL_MAX_CONTEXT = _env_float("ELEKTROSCAN_GRAY_WEAK_LABEL_MAX_CONTEXT", 0.23)
GRAY_WEAK_LABEL_MAX_PURITY = _env_float("ELEKTROSCAN_GRAY_WEAK_LABEL_MAX_PURITY", 0.58)
GRAY_TINY_GEOMETRY_MAX_TEMPLATE_PIXELS = _env_int(
    "ELEKTROSCAN_GRAY_TINY_GEOMETRY_MAX_TEMPLATE_PIXELS", 360
)
GRAY_TINY_GEOMETRY_MAX_SCALE = _env_float("ELEKTROSCAN_GRAY_TINY_GEOMETRY_MAX_SCALE", 0.55)
GRAY_TINY_GEOMETRY_MIN_MATCH = _env_float("ELEKTROSCAN_GRAY_TINY_GEOMETRY_MIN_MATCH", 0.59)
GRAY_TINY_GEOMETRY_MIN_VERIFICATION = _env_float(
    "ELEKTROSCAN_GRAY_TINY_GEOMETRY_MIN_VERIFICATION", 0.58
)
GRAY_TINY_GEOMETRY_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_TINY_GEOMETRY_MIN_COVERAGE", 0.98
)
GRAY_TINY_GEOMETRY_MIN_PURITY = _env_float("ELEKTROSCAN_GRAY_TINY_GEOMETRY_MIN_PURITY", 0.50)
GRAY_TINY_GEOMETRY_MIN_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_TINY_GEOMETRY_MIN_CONTEXT", 0.23
)
GRAY_STRONG_TRACE_MAX_ITEMS = _env_int("ELEKTROSCAN_GRAY_STRONG_TRACE_MAX_ITEMS", 40)
GRAY_FULLER_SYMBOL_MIN_AREA_RATIO = _env_float(
    "ELEKTROSCAN_GRAY_FULLER_SYMBOL_MIN_AREA_RATIO", 1.55
)
GRAY_FULLER_SYMBOL_MAX_VERIFICATION_DROP = _env_float(
    "ELEKTROSCAN_GRAY_FULLER_SYMBOL_MAX_VERIFICATION_DROP", 0.08
)
GRAY_FULLER_SYMBOL_MIN_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_FULLER_SYMBOL_MIN_COVERAGE", 0.94
)
GRAY_FULLER_SYMBOL_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_FULLER_SYMBOL_MIN_PURITY", 0.40
)
GRAY_SMALL_SCALE_HIGH_PURITY_MAX_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_HIGH_PURITY_MAX_COVERAGE", 0.90
)
GRAY_SMALL_SCALE_HIGH_PURITY_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_HIGH_PURITY_MIN_PURITY", 0.95
)
GRAY_SMALL_SCALE_HIGH_PURITY_MAX_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_HIGH_PURITY_MAX_CONTEXT", 0.30
)
GRAY_SMALL_SCALE_HIGH_PURITY_MAX_SCALE = _env_float(
    "ELEKTROSCAN_GRAY_SMALL_SCALE_HIGH_PURITY_MAX_SCALE", 0.90
)
GRAY_TINY_FRAGMENT_MAX_SCALE = _env_float("ELEKTROSCAN_GRAY_TINY_FRAGMENT_MAX_SCALE", 0.55)
GRAY_TINY_FRAGMENT_MAX_DIMENSION = _env_int(
    "ELEKTROSCAN_GRAY_TINY_FRAGMENT_MAX_DIMENSION", 22
)
GRAY_TINY_FRAGMENT_MAX_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_TINY_FRAGMENT_MAX_CONTEXT", 0.45
)
GRAY_SPARSE_TINY_FRAGMENT_MAX_SCALE = _env_float(
    "ELEKTROSCAN_GRAY_SPARSE_TINY_FRAGMENT_MAX_SCALE", 0.75
)
GRAY_SPARSE_TINY_FRAGMENT_MAX_DIMENSION = _env_int(
    "ELEKTROSCAN_GRAY_SPARSE_TINY_FRAGMENT_MAX_DIMENSION", 30
)
GRAY_SPARSE_TINY_FRAGMENT_MAX_DENSITY = _env_float(
    "ELEKTROSCAN_GRAY_SPARSE_TINY_FRAGMENT_MAX_DENSITY", 0.42
)
GRAY_SPARSE_TINY_FRAGMENT_MIN_ASPECT = _env_float(
    "ELEKTROSCAN_GRAY_SPARSE_TINY_FRAGMENT_MIN_ASPECT", 1.15
)
GRAY_LARGE_SCALE_PARTIAL_MIN_SCALE = _env_float(
    "ELEKTROSCAN_GRAY_LARGE_SCALE_PARTIAL_MIN_SCALE", 1.0
)
GRAY_LARGE_SCALE_PARTIAL_MAX_COVERAGE = _env_float(
    "ELEKTROSCAN_GRAY_LARGE_SCALE_PARTIAL_MAX_COVERAGE", 0.65
)
GRAY_LARGE_SCALE_PARTIAL_MIN_PURITY = _env_float(
    "ELEKTROSCAN_GRAY_LARGE_SCALE_PARTIAL_MIN_PURITY", 0.80
)
GRAY_LARGE_SCALE_PARTIAL_MIN_CONTEXT = _env_float(
    "ELEKTROSCAN_GRAY_LARGE_SCALE_PARTIAL_MIN_CONTEXT", 0.40
)

MIN_TEMPLATE_PIXELS = 20

MIN_COVERAGE_RATIO = 0.24
MIN_PURITY_RATIO = 0.08
MIN_CONTEXT_PURITY = 0.72
MIN_VERIFICATION_SCORE = 0.40
MAX_CENTROID_OFFSET_RATIO = 0.18
LOW_MATCH_STRICT_THRESHOLD = 0.58
CONTEXT_MARGIN_RATIO = 0.40

LOCAL_MAX_KERNEL_RATIO = 0.25

ROI_COMPONENT_DILATE_PIXELS = 9
ROI_MIN_COMPONENT_PIXELS = 6
ROI_MAX_COMPONENTS = 1200
ROI_MERGE_GAP_PIXELS = 4
ROI_PADDING_RATIO = 1.15
ROI_FULL_SCAN_AREA_RATIO = 0.70

# Gray-mode stroke suppression: MORPH_OPEN kernel sizes (pixels).
# Strokes longer than these thresholds are treated as text/dimension lines and
# removed from the scan mask before matchTemplate.  Symbols like 01/04/ZG have
# internal strokes shorter than this; text and dimension annotations are longer.
# Only affects the scan-time mask - validation still uses the raw ink mask.
GRAY_SUPPRESS_HORIZONTAL_KERNEL_PX = 40
GRAY_SUPPRESS_VERTICAL_KERNEL_PX = 40

PRECISE_KEYWORDS = ["gniazdo", "wypust"]
MIRRORED_VARIANT_PREFIXES = {"06", "07", "09", "10", "11", "12"}

COLOR_HUE_TOLERANCE = 18
COLOR_SAT_TOLERANCE = 80
COLOR_VAL_TOLERANCE = 80
COLOR_HUE_REJECTION_THRESHOLD = 36
SOCKET_07_EXTRA_MIN_COVERAGE = 0.30
SOCKET_07_PROMOTION_SEARCH_RADIUS = 4
SOCKET_PROMOTED_MAX_VERIFICATION_DROP = 0.05
SOCKET_07_STRONG_EXTRA_COVERAGE = 0.60
SOCKET_07_STRONG_MIN_COVERAGE = 0.80
SOCKET_07_STRONG_MIN_CONTEXT_PURITY = 0.25
SOCKET_07_STRONG_MAX_VERIFICATION_DROP = 0.16
SWITCH_10_EXTRA_MIN_COVERAGE = 0.18
SWITCH_12_EXTRA_MIN_COVERAGE = 0.18
SWITCH_PROMOTION_SEARCH_RADIUS = 8
SWITCH_FAMILY_MIN_CHILD_COVERAGE = 0.62
SWITCH_FAMILY_MIN_CROP_PURITY = 0.90
SWITCH_PROMOTED_MIN_PURITY = 0.58
SWITCH_PROMOTED_MIN_CONTEXT_PURITY = 0.22
SWITCH_PROMOTED_MIN_VERIFICATION = 0.62
SWITCH_10_PROMOTED_MAX_VERIFICATION_DROP = 0.06
SWITCH_12_PROMOTED_MAX_VERIFICATION_DROP = 0.18
SWITCH_PARENT_FALLBACK_SEARCH_RADIUS = 18
PROMOTED_PARENT_MIN_VERIFICATION = 0.68
PROMOTED_PARENT_OVERRIDE_MARGIN = 0.16
PROMOTED_PARENT_MIN_AREA_RATIO = 1.10
NOISY_PARTIAL_CONTEXT_THRESHOLD = 0.36
NOISY_PARTIAL_COVERAGE_THRESHOLD = 0.67
NOISY_PARTIAL_PURITY_THRESHOLD = 0.88

LABEL_TEMPLATE_MIN_ASPECT_RATIO = 1.25
LABEL_TEMPLATE_MIN_WIDTH = 40
LABEL_TEMPLATE_MAX_AREA = 5000
LABEL_LINE_MIN_RATIO = 0.18
LABEL_CONTENT_MIN_PIXELS = 18
LABEL_CONTENT_MIN_RATIO = 0.06
LABEL_CONTENT_MAX_RATIO = 0.72
LABEL_CONTENT_MIN_SCORE = 0.60
LABEL_FULL_WIDTH_CONTENT_MIN_SCORE = 0.50
LABEL_CONTENT_SCORE_WEIGHT = 0.55
LABEL_CONTENT_SCAN_MIN_PIXELS = 180
TEXT_LABEL_FULLER_AREA_RATIO = 1.12
TEXT_LABEL_FULLER_MAX_CONTENT_DROP = 0.08
TEXT_LABEL_FULLER_MAX_VERIFICATION_DROP = 0.08

PREFILTER_NMS_MIN_CANDIDATES = 250
PREFILTER_NMS_IOU_THRESHOLD = 0.85
RAW_PREFILTER_MIN_CANDIDATES = 1200
RAW_PREFILTER_IOU_THRESHOLD = 0.98
RAW_PREFILTER_IOM_THRESHOLD = 0.995
RAW_PREFILTER_CENTER_DISTANCE_RATIO = 0.04

CLUSTER_IOU_THRESHOLD = 0.30
CLUSTER_IOM_THRESHOLD = 0.72
CLUSTER_CENTER_DISTANCE_RATIO = 0.28
CROSS_COLOR_CLUSTER_IOU_THRESHOLD = 0.55
CROSS_COLOR_CLUSTER_IOM_THRESHOLD = 0.88
CROSS_COLOR_CENTER_DISTANCE_RATIO = 0.16


DEFAULT_PDF_DPI = 300
PDF_TEXT_MIN_TOKEN_LENGTH = 2
PDF_TEXT_MAX_TOKEN_LENGTH = 6
LEGEND_KEYWORD = "LEGENDA"
LEGEND_WIDTH_PT = 300
LEGEND_HEIGHT_PT = 550
