"""Compatibility facade for gray-PDF detector strategy helpers."""

from __future__ import annotations

from core.detector_gray_budget import _gray_budget_geometry_score, gray_raw_budget
from core.detector_gray_masks import (
    GrayLegendThresholds,
    GrayScanMasks,
    _clamp_roi,
    _clamp_threshold,
    _edge_band_densities,
    _estimate_gray_legend_thresholds,
    _gray_template_aspect,
    adapt_gray_tile_roi_strategy_for_plan,
    build_gray_scan_masks,
    gray_scan_threshold,
    gray_spatial_fair_peaks_per_roi,
    gray_template_area,
    gray_template_pixels,
    gray_tile_roi_strategy,
    is_gray_rect_frame_template,
    should_scan_gray_variant,
    use_gray_spatial_fair_peaks,
    use_large_text_tile_rois,
    use_lenient_gray_elongated_scan_threshold,
    use_raw_gray_scan_mask,
    use_relaxed_gray_scan_threshold,
)
from core.detector_gray_postprocess import (
    _center_inside_bbox,
    _compact_gray_hit_beats_large_partial,
    _dedupe_gray_overlapping_alternatives,
    _deep_same_ink_overlap,
    _filter_weak_gray_text_fragments,
    _hit_area,
    _hit_center,
    _is_complex_gray_geometry_hit,
    _is_full_gray_text_label_hit,
    _is_gray_frame_validated_rescue_hit,
    _is_gray_rect_frame_hit,
    _is_gray_rescue_blocked_by_existing,
    _is_gray_rescue_locally_dominated,
    _is_gray_symbol_hit,
    _is_mid_gray_geometry_hit,
    _is_same_template_duplicate_shadow,
    _is_strong_gray_label_geometry_hit,
    _is_tiny_gray_geometry_hit,
    _is_weak_gray_text_fragment,
    _merge_duplicate_gray_rect_frames,
    _nested_gray_fragment_loses_to_stronger_hit,
    _same_physical_hit,
    _same_template_close_shadow_loses_to_larger,
    _strong_compact_gray_hit_should_coexist,
    _suppress_nested_gray_core_hits,
    _weak_gray_compact_fragment_loses_to_larger,
    is_gray_frame_raw_rescue_hit,
    rescue_validated_gray_frame_hits,
    trace_unresolved_strong_gray_hits,
)
from core.detector_gray_rois import (
    GraySearchComponentIndex,
    _append_gray_tile_rois,
    _coalesce_gray_rois,
    _integral_rect_sum,
    _rect_area,
    _rect_intersection_area,
    _rect_union,
    build_gray_search_component_index,
    build_gray_search_rois,
    coalesce_gray_debug_rois,
)
